### ISSUE TITLE
azureml-sdk downgrades pyarrow to 3.0.0 which breaks cudf

### ISSUE THREAD

**Issue by mmccarty** [rapidsai/cloud-ml-examples#165]
### Steps to reproduce

1. Create a fresh RAPIDS conda environment <br/> `conda create -n rapids-22.06 -c rapidsai -c nvidia -c conda-forge rapids=22.06 python=3.8 cudatoolkit=11.5`
2. `conda activate rapids-22.06`
3. `conda list | grep pyarrow` shows 7.0.0 installed
4. Launch python/ipython and `import cudf` should work
5. `pip install azureml-sdk`
6. Launch python/ipython and `import cudf` fails
7. `conda list | grep pyarrow` shows 3.0.0 installed

#### Error:
```
$ python -m cudf
Traceback (most recent call last):
  File "/home/mmccarty/miniconda3/envs/cloud-ml-examples-test/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/mmccarty/miniconda3/envs/cloud-ml-examples-test/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/mmccarty/miniconda3/envs/cloud-ml-examples-test/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/mmccarty/miniconda3/envs/cloud-ml-examples-test/lib/python3.8/site-packages/cudf/__init__.py", line 13, in <module>
    from cudf import api, core, datasets, testing
  File "/home/mmccarty/miniconda3/envs/cloud-ml-examples-test/lib/python3.8/site-packages/cudf/datasets.py", line 7, in <module>
    from cudf._lib.transform import bools_to_mask
  File "/home/mmccarty/miniconda3/envs/cloud-ml-examples-test/lib/python3.8/site-packages/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
  File "cudf/_lib/avro.pyx", line 1, in init cudf._lib.avro
  File "cudf/_lib/column.pyx", line 1, in init cudf._lib.column
  File "cudf/_lib/scalar.pyx", line 37, in init cudf._lib.scalar
  File "cudf/_lib/interop.pyx", line 1, in init cudf._lib.interop
AttributeError: module 'pyarrow.lib' has no attribute 'MonthDayNanoIntervalArray'
```

**Comment by mmccarty** [comment]
Related to Azure/azure-sdk-for-python#25124

**Comment by zhimin-z** [comment]
### Steps to reproduce\r\n\r\n1. Create a fresh RAPIDS conda environment <br\/> `conda create -n rapids-22.06 -c rapidsai -c nvidia -c conda-forge rapids=22.06 python=3.8 cudatoolkit=11.5`\r\n2. `conda activate rapids-22.06`\r\n3. `conda list | grep pyarrow` shows 7.0.0 installed\r\n4. Launch python\/ipython and `import cudf` should work\r\n5. `pip install azureml-sdk`\r\n6. Launch python\/ipython and `import cudf` fails\r\n7. `conda list | grep pyarrow` shows 3.0.0 installed\r\n\r\n#### Error:\r\n```\r\n$ python -m cudf\r\nTraceback (most recent call last):\r\n  File \"\/home\/mmccarty\/miniconda3\/envs\/cloud-ml-examples-test\/lib\/python3.8\/runpy.py\", line 185, in _run_module_as_main\r\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\r\n  File \"\/home\/mmccarty\/miniconda3\/envs\/cloud-ml-examples-test\/lib\/python3.8\/runpy.py\", line 144, in _get_module_details\r\n    return _get_module_details(pkg_main_name, error)\r\n  File \"\/home\/mmccarty\/miniconda3\/envs\/cloud-ml-examples-test\/lib\/python3.8\/runpy.py\", line 111, in _get_module_details\r\n    __import__(pkg_name)\r\n  File \"\/home\/mmccarty\/miniconda3\/envs\/cloud-ml-examples-test\/lib\/python3.8\/site-packages\/cudf\/__init__.py\", line 13, in <module>\r\n    from cudf import api, core, datasets, testing\r\n  File \"\/home\/mmccarty\/miniconda3\/envs\/cloud-ml-examples-test\/lib\/python3.8\/site-packages\/cudf\/datasets.py\", line 7, in <module>\r\n    from cudf._lib.transform import bools_to_mask\r\n  File \"\/home\/mmccarty\/miniconda3\/envs\/cloud-ml-examples-test\/lib\/python3.8\/site-packages\/cudf\/_lib\/__init__.py\", line 4, in <module>\r\n    from . import (\r\n  File \"cudf\/_lib\/avro.pyx\", line 1, in init cudf._lib.avro\r\n  File \"cudf\/_lib\/column.pyx\", line 1, in init cudf._lib.column\r\n  File \"cudf\/_lib\/scalar.pyx\", line 37, in init cudf._lib.scalar\r\n  File \"cudf\/_lib\/interop.pyx\", line 1, in init cudf._lib.interop\r\nAttributeError: module 'pyarrow.lib' has no attribute 'MonthDayNanoIntervalArray'\r\n```

**Comment by jacobtomlinson** [comment]
It looks like `azureml-sdk` has been superseded by `azure-ai-ml` so this ticket should be closed by  https://github.com/rapidsai/deployment/pull/181.
